# Generated by Django 5.2.8 on 2025-11-26 16:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название услуги"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("duration", models.DurationField(verbose_name="Продолжительность")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "category",
                    models.CharField(
                        default="Общая", max_length=100, verbose_name="Категория"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="services/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="Можно указать ссылку на изображение из интернета",
                        max_length=500,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                        verbose_name="Ссылка на изображение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Фамилия"
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("hair", "💇 Парикмахер"),
                            ("nails", "💅 Ногтевой сервис"),
                            ("cosmetology", "✨ Косметология"),
                            ("massage", "💆 Массаж"),
                            ("eyebrows", "✏️ Брови и ресницы"),
                            ("makeup", "💄 Визаж"),
                        ],
                        max_length=50,
                        verbose_name="Специализация",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Рекомендуемый размер: 400x400px",
                        null=True,
                        upload_to="masters/photos/",
                        verbose_name="Фото мастера",
                    ),
                ),
                (
                    "photo_url",
                    models.URLField(
                        blank=True,
                        help_text="Можно указать ссылку на фото из интернета",
                        max_length=500,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                        verbose_name="Ссылка на фото",
                    ),
                ),
                (
                    "experience",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(50)],
                        verbose_name="Опыт работы (лет)",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=5.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Рейтинг",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Краткое описание опыта и специализации",
                        verbose_name="Описание мастера",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Чем меньше число, тем выше в списке",
                        verbose_name="Порядок отображения",
                    ),
                ),
                (
                    "instagram",
                    models.CharField(
                        blank=True,
                        help_text="Имя пользователя без @",
                        max_length=100,
                        verbose_name="Instagram",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^[\\+]?[0-9]{10,15}$"
                            )
                        ],
                        verbose_name="Телефон мастера",
                    ),
                ),
                (
                    "work_schedule",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON с графиком работы",
                        null=True,
                        verbose_name="График работы",
                    ),
                ),
                (
                    "services",
                    models.ManyToManyField(
                        blank=True,
                        related_name="masters",
                        to="app.service",
                        verbose_name="Услуги",
                    ),
                ),
            ],
            options={
                "verbose_name": "Мастер",
                "verbose_name_plural": "Мастера",
                "ordering": ["display_order", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="MasterSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Понедельник"),
                            (1, "Вторник"),
                            (2, "Среда"),
                            (3, "Четверг"),
                            (4, "Пятница"),
                            (5, "Суббота"),
                            (6, "Воскресенье"),
                        ],
                        verbose_name="День недели",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Время начала")),
                ("end_time", models.TimeField(verbose_name="Время окончания")),
                (
                    "is_working",
                    models.BooleanField(default=True, verbose_name="Рабочий день"),
                ),
                (
                    "master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="app.master",
                        verbose_name="Мастер",
                    ),
                ),
            ],
            options={
                "verbose_name": "График работы мастера",
                "verbose_name_plural": "Графики работы мастеров",
                "ordering": ["master", "day_of_week"],
                "unique_together": {("master", "day_of_week")},
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(
                        max_length=200,
                        validators=[django.core.validators.MinLengthValidator(2)],
                        verbose_name="Имя клиента",
                    ),
                ),
                (
                    "client_email",
                    models.EmailField(max_length=254, verbose_name="Email клиента"),
                ),
                (
                    "client_phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^[\\+]?[0-9]{10,15}$"
                            )
                        ],
                        verbose_name="Телефон клиента",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                ("time", models.TimeField(verbose_name="Время")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "⏳ Ожидает подтверждения"),
                            ("confirmed", "✅ Подтверждена"),
                            ("completed", "🎉 Выполнена"),
                            ("cancelled", "❌ Отменена"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
                (
                    "master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.master",
                        verbose_name="Мастер",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.service",
                        verbose_name="Услуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
                "ordering": ["-created_at"],
                "unique_together": {("master", "date", "time")},
            },
        ),
    ]
