# Generated by Django 4.2.8 on 2025-11-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='master',
            options={},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.AddField(
            model_name='master',
            name='experience',
            field=models.IntegerField(default=0, verbose_name='Опыт работы (лет)'),
        ),
        migrations.AddField(
            model_name='master',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='master',
            name='services',
            field=models.ManyToManyField(related_name='masters', to='app.service', verbose_name='Услуги'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(default='Общая', max_length=100, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Изображение'),
        ),
    ]
