# Generated by Django 4.2.8 on 2025-11-26 10:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_alter_master_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.AlterModelOptions(
            name='master',
            options={'ordering': ['display_order', 'user__first_name'], 'verbose_name': 'Мастер', 'verbose_name_plural': 'Мастера'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлена'),
        ),
        migrations.AddField(
            model_name='master',
            name='description',
            field=models.TextField(blank=True, help_text='Краткое описание опыта и специализации', verbose_name='Описание мастера'),
        ),
        migrations.AddField(
            model_name='master',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='Порядок отображения'),
        ),
        migrations.AddField(
            model_name='master',
            name='instagram',
            field=models.CharField(blank=True, help_text='Имя пользователя без @', max_length=100, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='master',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='master',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(regex='^[\\+]?[0-9]{10,15}$')], verbose_name='Телефон мастера'),
        ),
        migrations.AddField(
            model_name='master',
            name='work_schedule',
            field=models.JSONField(blank=True, default=dict, help_text='JSON с графиком работы', null=True, verbose_name='График работы'),
        ),
        migrations.AlterField(
            model_name='master',
            name='experience',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50)], verbose_name='Опыт работы (лет)'),
        ),
        migrations.AlterField(
            model_name='master',
            name='photo',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер: 400x400px', null=True, upload_to='masters/photos/', verbose_name='Фото мастера'),
        ),
        migrations.AlterField(
            model_name='master',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='master',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='masters', to='app.service', verbose_name='Услуги'),
        ),
        migrations.AlterField(
            model_name='master',
            name='specialization',
            field=models.CharField(choices=[('hair', '💇 Парикмахер'), ('nails', '💅 Ногтевой сервис'), ('cosmetology', '✨ Косметология'), ('massage', '💆 Массаж'), ('eyebrows', '✏️ Брови и ресницы'), ('makeup', '💄 Визаж')], max_length=50, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='master',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='MasterSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('is_working', models.BooleanField(default=True, verbose_name='Рабочий день')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='app.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'График работы мастера',
                'verbose_name_plural': 'Графики работы мастеров',
                'ordering': ['master', 'day_of_week'],
                'unique_together': {('master', 'day_of_week')},
            },
        ),
    ]
