# Generated by Django 4.2.8 on 2025-11-26 10:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_booking_options_alter_master_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='photo_url',
            field=models.URLField(blank=True, help_text='Можно указать ссылку на фото из интернета', max_length=500, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Ссылка на фото'),
        ),
        migrations.AddField(
            model_name='service',
            name='image_url',
            field=models.URLField(blank=True, help_text='Можно указать ссылку на изображение из интернета', max_length=500, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Ссылка на изображение'),
        ),
    ]
